kylef/swiftenv

libexec/swiftenv

Fixes
```
/usr/local/Cellar/swiftenv/0.2.0/bin/../libexec/swiftenv-global: line 22: /Users/mkida/.swiftenv/version: No such file or directory
```
When trying to set global version without creating `~/.swiftenv` prior to first use.

Create `.swiftenv` folder on first invoke

---

README.md

[The old link](https://swift.org/downloads) doesn't work anymore, they updated it to https://swift.org/download/

README: updated Swift download page link

---

README.md

In the 0.5.0 release, swiftenv now accepts URLs to swift binary packages from swift.org, this was stated in the release notes but not yet updated in the README.md

swiftenv install parameter description

---

CHANGELOG.md
libexec/swiftenv-rehash

This pull request changes how rehash works. Previously we created a shim for all executables found in a Swift version, toolchain or Xcode release. We will now only create shims which match swift* or lldb*.
I'm concerned that this may break some other tools where they are expecting some executables which may differ per swift (not sure if there are any).

Whitelist swift and lldb shims during rehash

---

libexec/swiftenv-install

I couldn't get it to work on osx because https://swiftenv-api.fuller.li/versions/3.0-GM-CANDIDATE/binaries/osx doesn't return a URL but it works on linux.

Support for swift 3.0 GM candidate on Linux

---

libexec/swiftenv-install
test/install.bats

This pull request greatly simplifies the logic in `swiftenv install`.
- Adds the `--verbose` option, to help users understand which version and URL will be installed while using `swiftenv install`.
- Error when lsb release binary is found but `/etc/lsb-release` exists to catch `lsb-release` package uninstalled on Ubuntu (aka, in the core docker image).
- Use swiftenv API to determine URL for a binary release to remove the logic to do this locally.
- Support setting `PLATFORM` environ to force a specific platform.
- Improve test coverage of install to handle `--list` and some more states.
This should solve #56, #58, and #60.

Simplify and improve `swiftenv install`

---

libexec/swiftenv-install
share/swiftenv-install/3.0

This changes the login to support downloading stable versions of Swift without hitting the API when we can detect a compatible binary for the current platform.

Support installing stable/known Swift binaries without hitting API

---

docs/commands.md
libexec/swiftenv-install
share/man/man1/swiftenv-install.1
share/swiftenv-install/3.0.1

As requested in #64. The install command now accepts a verify option that will download and check the gpg signature. For security, we do not automatically install any keys during the swift installation step, and instead assume (with documentation) that they have been installed by the user out-of-band.
```bash
$ swift install 2.2 --verify
```

Add "--verify" option for installations.

---

README.md

There was a weird non-space character that was throwing off the MarkDown parser.

Fix ReadMe markdown.

---

docs/installation.md

Using `.` in fish is deprecated:
https://fishshell.com/docs/current/commands.html#source
> . (a single period) is an alias for the source command. The use of . is deprecated in favour of source, and . will be removed in a future version of fish.

Remove dot command, improve fishconfig addition

---

libexec/swiftenv-init
test/init.bats

Change to make swiftenv work with fish 2.6.
See:
- https://github.com/pyenv/pyenv-virtualenv/issues/216
- https://github.com/pyenv/pyenv-virtualenv/pull/218

Change setenv to set -gx

---

CHANGELOG.md
libexec/swiftenv-install
share/man/man1/swiftenv-install.1
test/install.bats

You can now instruct `swiftenv install` to both locally and globally set the installed swift version. `--set-local` and `--set-global` respectively will set the current Swift version.
The default behaviour will set the global version by default when `swiftenv install` was provided an explicit version. When installing with the `SWIFT_VERSION` environment value or the `.swift-version` file present, then the default behaviour is to not set the global or local version.
Closes #83

Allow configuring when global/local is set during `swiftenv install`

---

libexec/swiftenv-install

* Now they should retrieve the correct upstream version they are based on.
* Behavior for pure Ubuntu distros is unaffected.

Added support for Ubuntu-based distros

---

libexec/swiftenv-install
share/man/man1/swiftenv-install.1
test/install.bats

I want `install -l` as a short option of `install --list` in swiftenv. It exists also in pyenv and other implementations.
This option behaves as follows.
```sh
$ swiftenv install -l
2.2-dev
2.2
2.2.1
3.0-dev
3.0
3.0.1
3.0.2
3.1-dev
3.1
3.1.1
4.0-dev
4.0
4.0.2
4.0.3
4.1-dev
4.1
4.2-dev
5.0-dev
```
swiftenv is very useful for me. Thanks to maintenance. 😄

Add short option to 'install --list'

---

Makefile
libexec/swiftenv-install

To get this to work I had to make two changes
1) Instead of using `lsb_release` to identify which Linux we are running I parse the `/etc/os-release` file. This file is more likely to be available. 
2) I don't use ask `swiftenv-api.fuller.li` to get the URL for the swift release. The swift team have a standard naming scheme for swift releases so you should need to create a new entry for each new release of swift.
Closes #138, #172

Add support for Centos7/8, Amazonlinux2 and aarch64

---

libexec/swiftenv-prefix

With the new swift driver running 'swift --version' will always print "swift-driver version: X.Y.Z" to stderr before printing the normal version info to stdout.
This causes all of the version checks as swiftenv runs to print the driver over and over.
The other option is to instead pass the flag '-disallow-use-new-driver' but at some point the new driver will most likely become the only driver so this future proofs against that.

Redirect 'swift --version' stderr to /dev/null

---

libexec/swiftenv-install

The output of `lscpu` is localized. It means that `lscpu | grep Architecture` may return an empty result.
Resolves [#185](https://github.com/kylef/swiftenv/issues/185).

Disable localization of `lscpu`.

---

libexec/swiftenv-install

Fixes URL for ARM64 Linux binaries. Neither Windows or macOS binaries are affected.
---
Running `swiftenv install 5.7` on ARM64 Ubuntu results in:
```diff
- Downloading https://download.swift.org/swift-5.7-release/ubuntu2004/swift-5.7-RELEASE/swift-5.7-RELEASE-ubuntu20.04-aarch64.tar.gz
+ Downloading https://download.swift.org/swift-5.7-release/ubuntu2004-aarch64/swift-5.7-RELEASE/swift-5.7-RELEASE-ubuntu20.04-aarch64.tar.gz
```
Which leads to successful installation.
<details><summary><h3>The problem</h3></summary>
Installing a version using `swiftenv 1.5.0` results in downloading a "Not found" web page instead of the binary, which then fails the installation:
```
/tmp/swiftenv-5.7- ~
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total …
```

Fix URL for ARM64 Linux binaries

---

libexec/swiftenv

Support commonly used XDG spec on Linux - if `XDG_DATA_HOME` is set, then use `"${XDG_DATA_HOME}"/swiftenv` as `SWIFTENV_ROOT`, use `~/.swiftenv` otherwise
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

libexec/swiftenv: use XDG_DATA_HOME if it is set

---

libexec/swiftenv-install

This addresses #192
With only this change, `gpg` logs a (slightly) more promising message:
```
gpg: Signature made Thu 30 Mar 2023 10:28:52 PM UTC using RSA key ID ED3D1561
gpg: Can't check signature: No public key
```
I understand that in https://github.com/kylef/swiftenv/pull/74 this is the desired result as it is intentional that swiftenv will not download the public keys. It would be nice if swiftenv did have a utility to help make that easier, but I agree it doesn't need to be part of the `install` command.
If I then get the Swift public keys as described on [Swift.org](https://www.swift.org/install/linux/#installation-via-tarball), we see a successful verification:
```
gpg: Signature made Mon 12 Sep 2022 07:39:56 AM UTC using RSA key ID ED3D1561
gpg: Good signature from "Swift 5.x …
```

Actually verify tarball against PGP signature
